#!/bin/bash
COMMAND="$@"

if [ "${DEBUG-0}" != "0" ]; then
  echo "${COMMAND?}"
fi

LOCAL_TERRAFORM_OUTPUT_DIRECTORY="${PWD}/output"

# Generate empty folder and files to prevent creation as root user
mkdir -p "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}"
touch "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}/terraform.plan"

docker run \
  -v "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}:/opt/output/" \
  -e ARM_CLIENT_ID="${ARM_CLIENT_ID?}" \
  -e ARM_CLIENT_SECRET="${ARM_CLIENT_SECRET?}" \
  -e ARM_SUBSCRIPTION_ID="${ARM_SUBSCRIPTION_ID?}" \
  -e ARM_TENANT_ID="${ARM_TENANT_ID?}" \
  -e ARM_STORAGE_ACCOUNT_NAME="${ARM_STORAGE_ACCOUNT_NAME?}" \
  -e ARM_ACCESS_KEY="${ARM_ACCESS_KEY?}" \
  -e DEBUG="${DEBUG}" \
  -e ENVIRONMENT_NAME="${ENVIRONMENT_NAME}" \
  -e ENVIRONMENT_REGION="${ENVIRONMENT_REGION}" \
  ${COMMAND?}
