#!/bin/bash
COMMAND="$@"

if [ "${DEBUG-0}" != "0" ]; then
  echo "${COMMAND?}"
fi

docker run \
  -v ${PWD}/output:/stack/output/ \
  -e ARM_CLIENT_ID="${ARM_CLIENT_ID?}" \
  -e ARM_CLIENT_SECRET="${ARM_CLIENT_SECRET?}" \
  -e ARM_SUBSCRIPTION_ID="${ARM_SUBSCRIPTION_ID?}" \
  -e ARM_TENANT_ID="${ARM_TENANT_ID?}" \
  -e ARM_ACCESS_KEY="${ARM_ACCESS_KEY?}" \
  -e DEBUG="${DEBUG}" \
  -e ENVIRONMENT_REGION="centralus" \
  ${COMMAND?}
