#!/bin/bash
DOCKER_IMAGE=$1
TERRAFORM_COMMAND=$2

docker run \
  -v ${HOME}/.ssh:/root/.ssh \
  -v ${PWD}/output:/stack/output/ \
  -e ARM_CLIENT_ID=${ARM_CLIENT_ID?} \
  -e ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET?} \
  -e ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID?} \
  -e ARM_TENANT_ID=${ARM_TENANT_ID?} \
  -e ARM_ACCESS_KEY=${ARM_ACCESS_KEY?} \
  -e ENVIRONMENT_REGION="centralus" \
  ${DOCKER_IMAGE?} ${TERRAFORM_COMMAND?}
