#!/bin/bash
while read DOCKER_IMAGE_ID; do
  if [ ! -z "${DOCKER_IMAGE_ID}" ]; then
    docker rmi -f "${DOCKER_IMAGE_ID?}" > /dev/null
  fi
done <<< $(docker images | sed 1d | grep -v terraform | awk '{ print $3 }')

docker images
