#!/bin/bash
while read -r DOCKER_IMAGE_ID; do
  if [ -n "${DOCKER_IMAGE_ID}" ]; then
    docker rmi -f "${DOCKER_IMAGE_ID?}" > /dev/null
  fi
done <<< "$(docker images | sed 1d | grep -E "iac-stack" | awk '{ print $3 }')"

docker images
