#!/bin/bash

set -e

while read -r DOCKER_IMAGE_ID; do
  if [ -n "${DOCKER_IMAGE_ID}" ]; then
    docker rmi -f "${DOCKER_IMAGE_ID?}" > /dev/null
  fi
done <<< "$(docker images | sed 1d | grep "iac-stack.*sandbox" | awk '{ print $3 }')"

docker system prune -f > /dev/null
docker images | grep -E "REPOSITORY|iac-stack-demo|hashicorp\/terraform"

ORIGIN_PATH=${PWD}

cd ../build/base-image/ && ./build && echo ""

cd "${ORIGIN_PATH?}" || exit 1

cd ../build/custom-images/ && ./build && echo ""

cd "${ORIGIN_PATH?}" || exit 1

export DEBUG=1

while read -r DOCKER_IMAGE; do
  ./azrun ${DOCKER_IMAGE?} plan
  rm -rf output

  echo ""
done <<< "$(./list-images)"
