#!/bin/bash

ORIGIN_PATH=${PWD}

echo "ORIGIN_PATH....: ${ORIGIN_PATH?}"

cd ../build/base-image/

./build

cd ${ORIGIN_PATH?}

cd ../build/custom-image/

./build

cd ${ORIGIN_PATH?}

export DEBUG=1

while read -r DOCKER_IMAGE; do

  echo ${DOCKER_IMAGE}

  ./azrun ${DOCKER_IMAGE} plan

done <<< $(./list-images)
