#!/bin/bash

mkdir -p .terraform

docker run \
  -u $(id -u):$(id -g) \
  -v "${PWD}/.terraform":/terraform/.terraform/ \
  -v "${PWD}":/terraform \
  -w /terraform \
  hashicorp/terraform:1.0.5 init

docker run \
  -u $(id -u):$(id -g) \
  -v "${PWD}/.terraform":/terraform/.terraform/ \
  -v "${PWD}":/terraform \
  -w /terraform \
  hashicorp/terraform:1.0.5 plan -out /terraform/.terraform/terraform.plan

docker run \
  -u $(id -u):$(id -g) \
  -v "${PWD}/.terraform":/terraform/.terraform/ \
  -v "${PWD}":/terraform \
  -w /terraform \
  hashicorp/terraform:1.0.5 apply -auto-approve /terraform/.terraform/terraform.plan

ls -lha

find
