#!/bin/bash

mkdir -p .terraform

docker_run() {
  COMMAND="$@"

  docker run \
    -u $(id -u):$(id -g) \
    -v "${PWD}/.terraform":/terraform/.terraform/ \
    -v "${PWD}":/terraform \
    -w /terraform \
    hashicorp/terraform:1.0.5 ${COMMAND?}
}

TERRAFORM_PLAN_FILE="/terraform/.terraform/terraform.plan"

docker_run init

docker_run plan -out "${TERRAFORM_PLAN_FILE}"

docker_run apply -auto-approve "${TERRAFORM_PLAN_FILE}"

ls -lha

find .
