#!/bin/bash

[[ -d ./output ]] && sudo rm -rf output

git check-ignore $(find . -print | grep -v '.idea') | xargs -n 1 -I {} echo "[ -e {} ] && rm -rf {}" | sh

while read line; do
  if [[ ! -z "$line" ]]; then
    echo $line
    docker rmi -f $(awk '{ print $3 }' <<< $line) &> /dev/null
  fi
done <<< $(docker images | grep -E "iac-stack.*1.0.*")

echo ""

docker system prune -f &> /dev/null

echo ""

docker images

echo ""
