#!/bin/bash

[[ -d ./output ]] && sudo rm -rf output

docker_run() {
  docker run \
    -v ${PWD}/output:/stack/output/ \
    -e ARM_CLIENT_ID=${ARM_CLIENT_ID?} \
    -e ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET?} \
    -e ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID?} \
    -e ARM_TENANT_ID=${ARM_TENANT_ID?} \
    -e ARM_ACCESS_KEY=${ARM_ACCESS_KEY?} \
    iac-stack-stage:1.0.0 $1
}

docker_run plan

docker_run apply
