#!/bin/sh
TERRAFORM_COMMAND="${1-plan}"
TERRAFORM_PLAN_FILE="/stack/output/terraform.plan"

echo ""

terraform --version

echo ""
echo "Environment"
echo "- user....: $(whoami)"
echo "- workdir.: $(pwd)"
echo "- command.: ${TERRAFORM_COMMAND}"
echo ""

echo "Backend Configuration"
echo ""
echo "/stack/backend.conf:"
cat /stack/backend.conf

terraform init -reconfigure -upgrade=false -backend-config /stack/backend.conf

if [ "${TERRAFORM_COMMAND}" == "apply" ]; then
  terraform apply -auto-approve ${TERRAFORM_PLAN_FILE?}
  terraform apply -auto-approve -refresh-only
else
  terraform plan -out ${TERRAFORM_PLAN_FILE?}
fi
